# Generated by Django 5.2.14 on 2026-05-15 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextualizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.TextField()),
                ('context', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='es', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Ok'), ('not_verifiable', 'Not Verifiable'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_verifiable', models.BooleanField(null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('final_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('x_field', models.CharField(max_length=100)),
                ('y_field', models.CharField(max_length=100)),
                ('color_field', models.CharField(blank=True, max_length=100, null=True)),
                ('facet_field', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight', models.CharField(blank=True, max_length=20, null=True)),
                ('top_n', models.SmallIntegerField(null=True)),
                ('chart_spec', models.JSONField(null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_selection', to='api.contextualizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='DatawrapperChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.CharField(max_length=20)),
                ('chart_url', models.URLField(max_length=500)),
                ('embed_code', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datawrapper_chart', to='api.contextualizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedDataContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=100)),
                ('indicator_name', models.CharField(max_length=500)),
                ('database_id', models.CharField(max_length=50)),
                ('database_name', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True, default='')),
                ('periodicity', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('start_year', models.SmallIntegerField(null=True)),
                ('end_year', models.SmallIntegerField(null=True)),
                ('area_codes', models.JSONField(default=list)),
                ('columns', models.JSONField(default=list)),
                ('records', models.JSONField(default=list)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_context', to='api.contextualizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField()),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField()),
                ('result', models.JSONField(null=True)),
                ('called_at', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='api.contextualizationrun')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
    ]
